name: Generar Keystore

on:
  workflow_dispatch:

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generar keystore
        run: |
          keytool -genkeypair -v \
            -keystore release.keystore \
            -alias canalesperu \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass canales2024 \
            -keypass canales2024 \
            -dname "CN=Canales Peru Vivo, OU=Dev, O=CanalesPeru, L=Lima, ST=Lima, C=PE"

      - name: Convertir a Base64
        run: |
          base64 release.keystore > keystore.b64
          echo "===== COPIA DESDE AQUI ====="
          cat keystore.b64
          echo "===== HASTA AQUI ====="

      - name: Subir keystore como artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: release.keystore
